### ISSUE TITLE
As an author, posts I create can be private to another author

### ISSUE THREAD

**Issue by ghost** [CMPUT404F16T04/sturdy-octo-computing-machine#10]
This user story is associated with:
- [As an author, posts I create can be public](https://github.com/CMPUT404F16T04/sturdy-octo-computing-machine/issues/16)
- [As an author, posts I create can be private to me](https://github.com/CMPUT404F16T04/sturdy-octo-computing-machine/issues/9)
- [As an author, posts I create be private to my friends](https://github.com/CMPUT404F16T04/sturdy-octo-computing-machine/issues/12)
- [As an author, posts I create be private to friends of friends](https://github.com/CMPUT404F16T04/sturdy-octo-computing-machine/issues/14)
- [As an author, posts I create be private to only friends on my host](https://github.com/CMPUT404F16T04/sturdy-octo-computing-machine/issues/41)

The following user stories depend on this one:
- [As an author I should be able to browse the posts of others depending on my status](https://github.com/CMPUT404F16T04/sturdy-octo-computing-machine/issues/30)

**Comment by carsonmclean** [comment]
But there is no visibility code for private to a specific author?
https://github.com/abramhindle/CMPUT404-project-socialdistribution/blob/master/example-article.json#L103

**Comment by carsonmclean** [comment]
Hindle said this is too difficult and no longer a req.
