### ISSUE TITLE
As a server admin, I want to share or not share images with users on other servers.

### ISSUE THREAD

**Issue by lexiebartlettt** [CMPUT404F16T04/sturdy-octo-computing-machine#13]
This user story is related to:
- [As a server admin, I want to share or not share posts with users on other servers](https://github.com/CMPUT404F16T04/sturdy-octo-computing-machine/issues/15)

**Comment by kobitoko** [comment]
dropped user story by TA & Prof.

https://eclass.srv.ualberta.ca/mod/forum/discuss.php?d=740313  

>Removed user stories
> by Joshua Campbell - Thursday, 24 November 2016, 4:56 PM  
> We are removing the following user stories:  
> * As an author, I want to feel safe about sharing images and posts with my friends - images should not publicly accessible without authentication.  
> * As a server admin, I want to share or not share images with users on other servers.  
> Images should be hotlinked from remote servers. E.g. your server should serve markdown with the image URL in it over the rest API to the user's server.  Server-server images are still required. Just not authentication for images.
