### ISSUE TITLE
As an author, I want a consistent identity per server

### ISSUE THREAD

**Issue by lexiebartlettt** [CMPUT404F16T04/sturdy-octo-computing-machine#20]

**Comment by carsonmclean** [comment]
Clarify???

**Comment by ghost** [comment]
Based on the example json provided in Hindle's repo I believe this is refering to UUID
https://en.wikipedia.org/wiki/Universally_unique_identifier 

For Example (taken from example-article.json):

```
A reponse if friends or not
Ask a service GET http://service/friends/<authorid>
responds with:
{
    "query":"friends",
    # Array of Author UUIDs
    "authors":[
        "de305d54-75b4-431b-adb2-eb6b9e546013",
        "ae345d54-75b4-431b-adb2-fb6b9e547891"
    ]
}
```

I was thinking we could make a class for UUID, where 1 field will be one-to-one with User and the other field will be UUID. Django docs say its not really good idea to make a custom User (https://docs.djangoproject.com/en/1.10/topics/auth/customizing/#extending-user), so this is the best solution I can think of.

About UUID in django: https://docs.djangoproject.com/en/1.10/ref/models/fields/#uuidfield

**Comment by ghost** [comment]
Each author is assigned a UUID
