### ISSUE TITLE
As an author, I want un-befriend local and remote authors

### ISSUE THREAD

**Issue by lexiebartlettt** [CMPUT404F16T04/sturdy-octo-computing-machine#22]
This user story depends on:
- [As an author, I want to befriend local authors](https://github.com/CMPUT404F16T04/sturdy-octo-computing-machine/issues/3)
- [As an author, I want to befriend remote authors](https://github.com/CMPUT404F16T04/sturdy-octo-computing-machine/issues/2)
- [As an author, my server will know about my friends](https://github.com/CMPUT404F16T04/sturdy-octo-computing-machine/issues/37)

**Comment by ghost** [comment]
This works for local authors.
When I unfriend someone, I am not longer their friend and I no longer am following them. They are still considered my follower until they unfollow my themselves.
