### ISSUE TITLE
As a server admin, I can limit nodes connecting to me via authentication.

### ISSUE THREAD

**Issue by ghost** [CMPUT404F16T04/sturdy-octo-computing-machine#25]
This user story depends on:
- [As a server admin, node to node connections can be authenticated with HTTP Basic Auth](https://github.com/CMPUT404F16T04/sturdy-octo-computing-machine/issues/23)

**Comment by kobitoko** [comment]
DOne with https://github.com/CMPUT404F16T04/sturdy-octo-computing-machine/commit/a4524aac63722c61027a5a6e9bcb6ae5ac3ecc3c

**Comment by kobitoko** [comment]
done with https://github.com/CMPUT404F16T04/sturdy-octo-computing-machine/commit/a4524aac63722c61027a5a6e9bcb6ae5ac3ecc3c  
Admin can create a node that has a user associated with it, the node when accessing api, needs to use that account for basic auth.

I gotta make sure ALL api endpoints have the basic-auth stuff and enforce it.
