### ISSUE TITLE
As a server admin, I want to be able to remove nodes and stop sharing with them.

### ISSUE THREAD

**Issue by ghost** [CMPUT404F16T04/sturdy-octo-computing-machine#26]
This user story depends on:
- [As a server admin, I want to be able to add nodes to share with](https://github.com/CMPUT404F16T04/sturdy-octo-computing-machine/issues/28)

**Comment by carsonmclean** [comment]
Clarify how we are doing authentication. Username and password for our entire server? Share details from their node's servers users? What about public posts on our server?

Public posts on our server can always be seen by any node, even not on our node list?

**Comment by kobitoko** [comment]
authentication for our server, theyre using basic auth, we store an account for them which they'll use for all their api calls.

However dunno if public posts on our server can always be seen... even not nodes gotta ask that to prof or TA.
