### ISSUE TITLE
As a server admin, I want to be able to add nodes to share with

### ISSUE THREAD

**Issue by ghost** [CMPUT404F16T04/sturdy-octo-computing-machine#28]
This user story is associated with:
- [As a server admin, node to node connections can be authenticated with HTTP Basic Auth](https://github.com/CMPUT404F16T04/sturdy-octo-computing-machine/issues/23)

This following user story depends on this one:
- [As a server admin, I want to be able to remove nodes and stop sharing with them.](https://github.com/CMPUT404F16T04/sturdy-octo-computing-machine/issues/26)

**Comment by kobitoko** [comment]
todo: store own user(our id & password for their basic auth) for access of foreign node, so when we connect to their nodes, we use that id and password.... however cannot use django;s auth_user as it stores password as SHA256, so we can't enter a SHA256 as a SHA256 of a SHA256 is different.... Need store pw as string?!?
