### ISSUE TITLE
As a server admin, I want to be able add, modify, and remove authors.

### ISSUE THREAD

**Issue by lexiebartlettt** [CMPUT404F16T04/sturdy-octo-computing-machine#29]
This user story is associated with:
- [As a server admin, I want to be able allow users to sign up but require my OK to finally be on my server](https://github.com/CMPUT404F16T04/sturdy-octo-computing-machine/issues/33)

**Comment by ghost** [comment]
Server admin can add, update, and delete authors.

Add: User drop down displays all users but validation does not allow you to assign a user to an author who is already assigned to an author.

Update: User, friends and who you are following are read-only to prevent the data from being put into a weird state.

Delete: The user account will also be deleted when an author is deleted.
