### ISSUE TITLE
As an author, I want to befriend local authors

### ISSUE THREAD

**Issue by lexiebartlettt** [CMPUT404F16T04/sturdy-octo-computing-machine#3]
The following user stories depend on this one:
- [As an author, When I befriend someone it follows them, only when the other authors befriends me do I count as a real friend.](https://github.com/CMPUT404F16T04/sturdy-octo-computing-machine/issues/36)
- [As an author, I want un-befriend local and remote authors](https://github.com/CMPUT404F16T04/sturdy-octo-computing-machine/issues/22)

This user story is associated with:
- [As an author, I want to befriend remote authors](https://github.com/CMPUT404F16T04/sturdy-octo-computing-machine/issues/2)
- [As an author, my server will know about my friends](https://github.com/CMPUT404F16T04/sturdy-octo-computing-machine/issues/37)
- [As an author, I want to know if I have friend requests.](https://github.com/CMPUT404F16T04/sturdy-octo-computing-machine/issues/32)

**Comment by ghost** [comment]
Authors can send each other friend requests by "following" them.

Pending friend requests are calculated by:
My followers - my friends - ignore list
- When someone becomes someone's friend, they become both their friend and their follower
- When you decline a friend request, it is added to the ignore list and the user will still be your follower. If you change your mind, you can still accept the friend request on the user's profile page.
