### ISSUE TITLE
As a server admin, I want to be able allow users to sign up but require my OK to finally be on my server

### ISSUE THREAD

**Issue by lexiebartlettt** [CMPUT404F16T04/sturdy-octo-computing-machine#33]
This user story is associated with:
- [As a server admin, I want to be able add, modify, and remove authors.](https://github.com/CMPUT404F16T04/sturdy-octo-computing-machine/issues/29)

**Comment by ghost** [comment]
When users register, a new user is created but it will in inactive.

A custom action is added to the Django Admin app. This will allow us to bulk approve users and see which users need to be approved on the User admin screen.

When a user is approved, their account is activated and automatically added to a new author model.
