### ISSUE TITLE
Post using certain characters like ( ͡° ͜ʖ ͡°) crashes + Can upload .exe!

### ISSUE THREAD

**Issue by kobitoko** [CMPUT404F16T04/sturdy-octo-computing-machine#49]
Don't do multipart formdata for text! e.g. ( ͡° ͜ʖ ͡°) lenney face breaks website because multipart does not encode.

> application/x-www-form-urlencoded     Default. All characters are encoded before sent (spaces are converted to "+" symbols, and special characters are converted to ASCII HEX values)
> 
> multipart/form-data   No characters are encoded. This value is required when you are using forms that have a file upload input

-Use AJAX for the additional image form after the post form and somehow still get result in views CreatePost form_valid? And have somehow be submit button post both post and image forms.

~~-Also use AJAX to retrieve the image instead of that hacky javascript iframe interaction I put in.~~

~~-Also Fix file type upload check/filtering, i can upload .exes etc....~~

**Comment by kobitoko** [comment]
Raises an validation error now when invalid image, need somehow redirect to an "you tried uploading an invalid image" html. 
But also try do primitive javascript file extension str check in the html too?

**Comment by ghost** [comment]
Ryan made a custom html page for now 👍

**Comment by kobitoko** [comment]
creating post wiht " ͜ʖ ͡`~( ͡° ͜ʖ ͡°)/\/~" does not break it anymore somehow.
puttted the above gibrish in all text content, description and title.
