### ISSUE TITLE
Project Part 1: Testing

### ISSUE THREAD

**Issue by ghost** [CMPUT404F16T04/sturdy-octo-computing-machine#54]
This covers our manual UI testing, to verify things are working as expected.

## General UI
This section tests that our UI can handle people making silly things.
**Really Long/Max Content** = No characters to indicate a break, such as a hyphen or space, are used.
- [x] Ensure author's with really long names are displayed appropriately on each page (post, friend request, profile)
- [x] Ensure post's with max content are displayed appropriately.
- [x] Ensure huge images that are attached to posts are displayed correctly.
- [x] Ensure huge images in markdown are displayed correctly.
- [x] If I view a page and there is nothing to display (no posts, no friends, no comments, etc), then this is stated in a text box somewhere.
- [x] Posts and comments are ordered by newest first. (List posts, profile page, view comments).

#### Included user stories:
As an author I want to make posts.
As an author, posts I make can be in simple plain text.
As an author, posts I make can be in markdown (commonMark is good).
As an author posts I create can be public.
As an author, I want to delete my own posts.
As an author, I want to be able to use my web-browser to manage/author my posts.
#### Tests:
- [x] A plain text post can be created.
- [x] A markdown post can be created.
- [x] A post with no content cannot be created.
- [x] Errors are handled correctly if an author attempts to submit a large amount of text by pasting it into the box and hitting Finish.
- [x] The author and timestamp are correct when a post is created.
- [x] Ensure that visibility can be selected when creating a post.
- [x] I can change a post I own after it has been created (Carson is working on this).
- [x] I can delete my posts from the home page. (Security will be checked later)
- [x] I can delete my posts from my profile page.
- [x] I can delete my post when viewing it individually.
- [x] When I delete a post, it also deletes any images associated with it.
- [x] When I delete a post, it also deletes any comments associated with it.

#### Included user stories:
As an author I should be able to browse the public posts of everyone.
As an author I want to post to my stream.
#### Tests:
- [x] Only public posts are displayed on the home page.
- [x] I can see anyone's public posts (I do not need to be their friend or follower) on the Home page.
- [x] On the home page, all posts are not loaded at once (pagination or lazy loading is used to my browser isn't lagging).

_Note: On a profile page currently only "friends", "public", and "private" is implemented in terms of post visibility._
- [x] On an author's profile page, only the author's posts are displayed.
- [x] If I am viewing my own profile page, I can see all of my posts (regardless of visibility).
- [x] If I am viewing another author's page and we have no relationship (not friends or followers), then I can only see posts marked as public.
- [x] If I am viewing another author's page and I am their follower (but we are not friends), then I can only see posts marked as public.
- [x] If I am viewing another author's page and I am their friend, then I can see public and friends-only posts.
- [x] If I am viewing another author's page, then I can never see posts that are marked as private.

#### Included user stories:
As an author, I want to comment on posts that I can access.
#### Tests:
- [x] I can add a comment to a post.
- [x] I can view comments for posts that contain them.

#### Included user stories:
As a server admin, images can be hosted by my server.
As an author, posts I create can link to images.
As an author, I want to feel safe about sharing images and posts with my friends – images should not publicly accessible without authentication
#### Tests:
- [x] I can create a post with linked images in the markup.
- [x] I can create a post with an attached image.
- [x] Images cannot be viewed if I am not logged in.
- [x] 2 authors can upload an image with the same file name without issue.
- [x] What happens when I try to upload a file that is not an image? (idk if/how we handle this)
- [x] What happens if I try to attach more than 1 image?

#### Included user stories:
As an author, I want to be able to use my web-browser to manage my profile.
#### Tests:
- [x] An author's profile is displayed on their page.
- [x] An author can edit their profile. (Security is checked in a later section)
- [x] Edit Profile: Errors are displayed correctly if an author enters an invalid date.
- [x] Edit Profile: Errors are handled correctly if an author attempts to submit a large amount of text by pasting it into a box and hitting Finish.

#### Included user stories:
As an author, other authors cannot modify my data.
#### Tests:
- [x] I cannot view any page (aside from login or register) if I am not logged in. Test this by pasting URLs in to the browser when not logged in. Check home page, profile page, view a single post, view comments, add comment, add post, delete post, view image, edit profile, manage friends, manage followers, manage friend requests.

_Here we want to check that links to these pages are not displayed if we shouldn't be able to access them. We also want to check that we cannot paste a url into the browser and edit things if we shouldn't be allowed to see that page._
- [x] I cannot manage someone else's friends.
- [x] I cannot access someone else's "who i'm following" page.
- [x] I cannot manage someone else's friend requests.
- [x] I cannot manage someone else's profile.
- [x] I cannot delete someone else's post on the home page.
- [x] I cannot delete someone else's post on the profile page.
- [x] I cannot delete someone else's post on the view post page. 
- [x] I cannot login with incorrect information and the correct error message is displayed.
- [x] I cannot login if my account has not been approved and the correct error message is displayed.

#### Included user stories:
As an author, When I befriend someone it follows them, only when the other authors befriends me do I count as a real friend.
As an author, I want to know if I have friend requests.
As an author, I want to befriend local authors.

_How the friend system works in our app: A follow is treated like a "friend request". When I follow someone, they are sent a friend request. When I accept a friend request I am both a friend and follower of the other author._
#### Tests:
- [x] If I have no relationship with someone, a "Follow" button is displayed on their profile page.
- [x] cont. from above: If I select the "Follow" button, it changes to "Unfollow" and I am now following them  (can verify easily by viewing author in django admin).
- [x] If I am a follower of someone, but we are not friends, then an "Unfollow" button is displayed on their profile page.
- [x] cont. from above: If I select the "Unfollow" button, it changes to "Follow" and I am no longer following them  (can verify easily by viewing author in django admin).
- [x] If I am a friend of someone, then an "Unfriend" button is displayed on their profile page.
- [x] cont. from above: If I select the "Unfriend" button, it changes to a "Accept Friend Request" button. We are no longer friends and I am no following them (can verify easily by viewing author in django admin).
- [x] If someone if following me, but I am not following them, then on their profile page is a "Accept Friend Request" button.
- [x] cont. from above: If I select the "Accept Friend Request" button, we are now friends and I am now following them (can verify easily by viewing author in django admin).
- [x] The number of pending friend requests I have is displayed in the nav bar.
- [x] Manage Friends page: When I un-friend someone, I am not longer their friend and I am no longer following them (can verify easily by viewing author in django admin)
- [x] Manage Friends page: When I un-friend someone the button changes to "Accept Friend Request". If I accept the friend request, I am their follower and friend (can verify easily by viewing author in django admin)
- [x] Manage Who I Am Following page: When I un-follow someone, I am no truly longer following them (can verify easily by viewing author in django admin).
- [x] Manage Who I Am Following page: When I un-follow someone, the button changes to Follow. If I follow them again, I am their follower (can verify easily by viewing author in django admin).
- [x] Manage Friend Requests page: When I accept a friend request, the author is no longer displayed on the page. I am now their follower and friend (can verify easily by viewing author in django admin).
- [x] Manage Friend Requests page: When I decline a friend request, the author is no longer displayed on the page. I am not their follower or friend (can verify easily by viewing author in django admin).
- [x] Manage Friend Requests page: When I decline a friend request, I can still accept it later by going to the author's profile page and selecting the Accept Friend Request button. I am now their follower and friend (can verify easily by viewing author in django admin).

#### Included user stories:
As a server admin, I want to be able allow users to sign up but require my OK to finally be on my server.
As a server admin, I want to be able add, modify, and remove authors.
As a server admin, I want to host multiple authors on my server.
#### Tests:
- [x] If I don't have an account, I can sign up on the registration page.
- [x] As an admin, I can see user's who have not been approved in django admin on the User list.
- [x] As an admin, I can approve user's by checking the box for each user I want to approve, then selecting the Approve Action (from the drop-down menu where delete is located).
- [x] As an admin I can delete an account by deleting the user. This will also delete the associated author if the account has been approved.
- [x] As an admin I can delete an account by deleting the author. This will also delete the associated user.
- [x] As an admin I can modify an author. (Note: friends, followers, and the associated user are not modifiable by design to protect state).
- [x] As an admin I can create new authors.

## Other
As an author, I want a consistent identity per server.
- [x] When a new author is created, they are assigned a UUID.

**Comment by kobitoko** [comment]
> Edit Profile: Errors are displayed correctly if an author enters an invalid date.
In firefox, since it does not support datetime input box it is just simply an empty textbox, it does not even say what format is, perhaps the text could say "Enter Birthday (yyyy-mm-dd)" or make that fields attribute
' value="yyyy-mm-dd" '

Little nitpick: the button in profile when saying edit, imo the button should say (save) cuz when i first saw that button i kinda got confused lol.
**I shall do these changes right naw

**Comment by kobitoko** [comment]
> "Edit Profile: Errors are handled correctly if an author attempts to submit a large amount of text by pasting it into a box and hitting Finish." 

Works for "About Me", but not for "Github url".
Also for some reason errors message is display twice (tho removing the inner error loop in html django pyhon fixes this, but if there are multiple errors per single field ever then well only first is displayed...?)

**Comment by carsonmclean** [comment]
>  What happens when I try to upload a file that is not an image? (idk if/how we handle this)

User gets redirected to a Django error page.

**Comment by ghost** [comment]
> What happens when I try to upload a file that is not an image? (idk if/how we handle this)
> User gets redirected to a Django error page.

This has been updated to display a user friendly error page.

Testing is completed 👍
