### ISSUE TITLE
Post API Endpoints

### ISSUE THREAD

**Issue by ghost** [CMPUT404F16T04/sturdy-octo-computing-machine#58]
_IMPORTANT NOTE:_ All of the post URIs will GET a list of posts. The following pagination style must be accepted:
`GET http://service/author/posts?page=4&size=50`
- If a page is provided, return the results for that page, if no page is provided return page 0
- If a size is provided, return pages in this size up to the maximum set on the server. If no size is provided return the default page size.

**Checklist** ([View Spec Here](https://github.com/abramhindle/CMPUT404-project-socialdistribution/blob/master/example-article.json))

- [x] `GET http://service/author/posts` (posts that are visible to the currently authenticated user)
- [x] `GET http://service/posts` (all posts marked as public on the server)
- [x] `GET http://service/author/{AUTHOR_ID}/posts` (all posts made by {AUTHOR_ID} visible to the currently authenticated user)
_Note_: FOAF Visibility: verification involves the 3 hosts of the 3 friends A->B->C assuming A B C reside on different hosts
- [x] `GET http://service/posts/{POST_ID}` access to a single post with id = {POST_ID}
- [x] Pagination works for all of the above URIs
- [x] I have unit tests for the above uri's in test_api.py

Under requirements: (??)
Implement a restful API for http://service/posts/postid
- a PUT should insert/update a post
- a POST should insert the post

**Comment by carsonmclean** [comment]
UPDATE:
As for the 4 GET's above, they have all been started except for /author/{AUTHOR_ID}/posts. Those that have been started are 75%+ done and just need checking for a few fields, use by external parties, etc. 
Pagination has also been implemented once for posts, so should be easy to replicate for comments, etc.

**Comment by kobitoko** [comment]
I made /author/{authorid}/posts and GET post/{postid}/comments
Using Carsons serializers.
