### ISSUE TITLE
Image Sizes in Comments Overflows Comment Area

### ISSUE THREAD

**Issue by carsonmclean** [CMPUT404F16T04/sturdy-octo-computing-machine#62]
![screen shot 2016-11-17 at 1 41 52 pm](https://cloud.githubusercontent.com/assets/11656251/20406756/bebb28c0-accb-11e6-8dc0-6c31b2be4847.png)

**Comment by carsonmclean** [comment]
@vbobey found this.

**Comment by kobitoko** [comment]
I fixed that when overhauling the image stuff after requirements removed.
https://github.com/CMPUT404F16T04/sturdy-octo-computing-machine/commit/2667c76b929c8a9e2bc348b040b86916b29fd406
