### ISSUE TITLE
As an author, posts I create can link to images

### ISSUE THREAD

**Issue by ghost** [CMPUT404F16T04/sturdy-octo-computing-machine#7]

**Comment by kobitoko** [comment]
Question:
Link to images in simple plain text post?
Because commonmark markdown already can link images via markdown.

**Comment by ghost** [comment]
Josh says all images should be hosted on our server

**Comment by kobitoko** [comment]
Image links will be literally links hopefully that is ok, (attaching them as <img> has some challenge within posts because the way made the image available to ensure authentication)
